### ISSUE TITLE
Merge NEMO source

### ISSUE THREAD

**Issue by erik808** [oceandie/BALTIC-MEs#6]
NEMO is here twice. Can I merge those two sources without any problems? (`NEMO_4.0.4_hpge_ovf, NEMO_4.0-HEAD_test_MEs`) Or does the adapted DOMAIN tool need a vanilla NEMO to function?

**Comment by oceandie** [comment]
They are two different versions of NEMO: `NEMO_4.0.4_hpge_ovf` is a branch of NEMO_4.0.4 while `NEMO_4.0-HEAD_test_MEs` is branched from NEMO_4.0-HEAD. In theory DOMAINcfg tool should work fine with both - but this should be tested first ...

**Comment by erik808** [comment]
I'll see if I can merge the DOMAINcfg tool in 4.0.4 and I'll test :)
